/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import luigi.trabalhofinal.classes.Curso;
import luigi.trabalhofinal.classes.Materia;
import luigi.trabalhofinal.classes.ServidorPublico;
import luigi.trabalhofinal.classes.Universidade;

/**
 *
 * @author luigi
 */
public class MenuGerencia extends javax.swing.JFrame {

    Universidade uffs = new Universidade("UFFS", "Xilindró"); // Define uma nova universidade.

    /**
     * Creates new form MenuGerencia
     */
    public MenuGerencia() {
        initComponents();

        uffs.contratar(new ServidorPublico("Seu Antonio", "25/03/1940", "Professor PHD", 19000));
        uffs.adicionarMateriaComum(new Materia("Economia e sosiedad", "910B", "Tarde", 4)); // Adiciona uma matéria comum a todos os cursos da universidade.

        Curso cc = new Curso("cc"); // Define um novo curso.

        cc.adicionarMateria(new Materia("matematica secreta", "310B", "Tarde", 20)); // Adiciona uma matéria específica a esse curso.

        uffs.adicionarCurso(cc); // Adiciona o novo curso à universidade.

        nServidoresLabel.setText("Servidores: " + uffs.getNServidores());
        nAlunosLabel.setText("Alunos: " + uffs.getNAlunos());
        nBlocosLabel.setText("Blocos: " + uffs.getNBlocos());
        nCursosLabel.setText("Cursos: " + uffs.getNCursos());

        uffs.imprimirCursos();
        uffs.imprimirMateriasComuns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeUniversidadeLabel = new javax.swing.JLabel();
        nServidoresLabel = new javax.swing.JLabel();
        nAlunosLabel = new javax.swing.JLabel();
        nBlocosLabel = new javax.swing.JLabel();
        nCursosLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        contratarServidor = new javax.swing.JMenuItem();
        relatorioServidor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        matricularAluno = new javax.swing.JMenuItem();
        relatorioAluno = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        construirBloco = new javax.swing.JMenuItem();
        relatorioBloco = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Gerência");

        nomeUniversidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        nomeUniversidadeLabel.setText("Universidade Federal da Fronteira Sul");

        nServidoresLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nServidoresLabel.setText("Servidores: 0");

        nAlunosLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nAlunosLabel.setText("Alunos: 0");

        nBlocosLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nBlocosLabel.setText("Blocos: 0");

        nCursosLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nCursosLabel.setText("Cursos: 0");

        jMenu1.setText("Servidores");

        contratarServidor.setText("Contratar");
        contratarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarServidorActionPerformed(evt);
            }
        });
        jMenu1.add(contratarServidor);

        relatorioServidor.setText("Relatório");
        relatorioServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioServidorActionPerformed(evt);
            }
        });
        jMenu1.add(relatorioServidor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alunos");

        matricularAluno.setText("Matricular");
        matricularAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricularAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(matricularAluno);

        relatorioAluno.setText("Relatório");
        relatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(relatorioAluno);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Blocos");

        construirBloco.setText("jMenuItem1");
        jMenu3.add(construirBloco);

        relatorioBloco.setText("Relatório");
        jMenu3.add(relatorioBloco);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cursos");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nServidoresLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeUniversidadeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nCursosLabel)
                            .addComponent(nBlocosLabel)
                            .addComponent(nAlunosLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nomeUniversidadeLabel)
                .addGap(24, 24, 24)
                .addComponent(nServidoresLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nAlunosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nBlocosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nCursosLabel)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contratarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contratarServidorActionPerformed

    private void relatorioServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioServidorActionPerformed
        // TODO add your handling code here:
        uffs.imprimirServidores();

    }//GEN-LAST:event_relatorioServidorActionPerformed

    private void matricularAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricularAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricularAlunoActionPerformed

    private void relatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioAlunoActionPerformed
        // TODO add your handling code here:
        uffs.imprimirAlunos();
    }//GEN-LAST:event_relatorioAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem construirBloco;
    private javax.swing.JMenuItem contratarServidor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem matricularAluno;
    private javax.swing.JLabel nAlunosLabel;
    private javax.swing.JLabel nBlocosLabel;
    private javax.swing.JLabel nCursosLabel;
    private javax.swing.JLabel nServidoresLabel;
    private javax.swing.JLabel nomeUniversidadeLabel;
    private javax.swing.JMenuItem relatorioAluno;
    private javax.swing.JMenuItem relatorioBloco;
    private javax.swing.JMenuItem relatorioServidor;
    // End of variables declaration//GEN-END:variables
}
